#!/usr/bin/env bash
# ============================================================================
# 02-nvidia-setup.sh — Configure NVIDIA drivers, DRM, mkinitcpio, boot params
# Run AFTER 01-system-packages.sh
# ============================================================================
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

[[ $EUID -eq 0 ]] && error "Do not run as root."

# ── mkinitcpio: add nvidia modules ───────────────────────────────────────────
info "Configuring mkinitcpio with NVIDIA modules..."

MKINITCPIO="/etc/mkinitcpio.conf"
MKINITCPIO_BACKUP="${MKINITCPIO}.bak.$(date +%Y%m%d%H%M%S)"
sudo cp "$MKINITCPIO" "$MKINITCPIO_BACKUP"
info "Backup created: $MKINITCPIO_BACKUP"

# Add NVIDIA modules without dropping existing MODULES entries
if grep -q "^MODULES=" "$MKINITCPIO"; then
    for mod in nvidia nvidia_modeset nvidia_uvm nvidia_drm; do
        if ! grep -Eq "^MODULES=.*\\b${mod}\\b" "$MKINITCPIO"; then
            sudo sed -i "/^MODULES=/ s/)/ ${mod})/" "$MKINITCPIO"
        fi
    done
else
    echo 'MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)' | sudo tee -a "$MKINITCPIO" >/dev/null
fi

info "Keeping existing HOOKS in mkinitcpio.conf unchanged."

info "Rebuilding initramfs..."
sudo mkinitcpio -P

# ── modprobe: nvidia-drm modeset + nouveau blacklist ─────────────────────────
info "Configuring modprobe for NVIDIA..."

# supergfxd auto-generates this, but ensure it exists
sudo mkdir -p /etc/modprobe.d

cat <<'EOF' | sudo tee /etc/modprobe.d/supergfxd.conf >/dev/null
# Automatically generated by supergfxd
blacklist nouveau
alias nouveau off

options nvidia-drm modeset=1
EOF

# AMD iGPU performance mode
cat <<'EOF' | sudo tee /etc/modprobe.d/amdgpu.conf >/dev/null
options amdgpu power_dpm_force_performance=1
EOF

info "Modprobe configs written."

# ── systemd-boot: add nvidia_drm.modeset=1 to kernel cmdline ────────────────
info "Checking systemd-boot entries for nvidia_drm.modeset=1..."

BOOT_ENTRIES_DIR="/boot/loader/entries"
if [[ -d "$BOOT_ENTRIES_DIR" ]]; then
    for entry in "$BOOT_ENTRIES_DIR"/*.conf; do
        [[ -f "$entry" ]] || continue
        if grep -q "^options " "$entry"; then
            if ! grep -q "nvidia_drm.modeset=1" "$entry"; then
                info "Adding nvidia_drm.modeset=1 to $entry"
                sudo sed -i '/^options / s/$/ nvidia_drm.modeset=1/' "$entry"
            else
                info "nvidia_drm.modeset=1 already present in $entry"
            fi
            # Also add acpi_backlight=native if not present (laptop backlight fix)
            if ! grep -q "acpi_backlight=native" "$entry"; then
                info "Adding acpi_backlight=native to $entry"
                sudo sed -i '/^options / s/$/ acpi_backlight=native/' "$entry"
            fi
        fi
    done
else
    warn "No systemd-boot entries found at $BOOT_ENTRIES_DIR. If using GRUB, add nvidia_drm.modeset=1 to GRUB_CMDLINE_LINUX_DEFAULT manually."
fi

# ── Enable NVIDIA power management services ─────────────────────────────────
info "Enabling NVIDIA power management services..."
nvidia_services=(
    nvidia-suspend.service
    nvidia-resume.service
    nvidia-hibernate.service
)

for svc in "${nvidia_services[@]}"; do
    if systemctl list-unit-files "$svc" >/dev/null 2>&1; then
        sudo systemctl enable "$svc"
    else
        warn "Service not found: $svc (skipping)"
    fi
done

# ── Enable supergfxd for hybrid GPU switching ────────────────────────────────
info "Enabling supergfxd..."
if systemctl list-unit-files supergfxd.service >/dev/null 2>&1; then
    sudo systemctl enable supergfxd.service
else
    warn "Service not found: supergfxd.service (skipping)"
fi

info "NVIDIA setup complete!"
info "A reboot is required for changes to take effect."
